name: Binary build

on:
  push:
    branch:
      - 'main'
      - 'stable'

env:
  CARGO_TERM_COLOR: always

jobs:

  cross-build:
    name: Publish binary builds
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ["x86_64-unknown-linux-gnu", "i686-unknown-linux-gnu", "aarch64-unknown-linux-gnu", "armv7-unknown-linux-gnueabihf", "x86_64-pc-windows-gnu"]
    steps:
      - uses: actions/checkout@v2
      - name: Install rust 1.70.0
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.70.0
          override: true
      - name: Download renamer
        run: curl -sSf https://raw.githubusercontent.com/memflow/memflowup/master/target_rename.sh > target_rename.sh
      - name: Build artifacts
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --all-features --workspace --verbose --target ${{ matrix.target }}
      - name: Rename and collect artifacts
        id: artifacts
        run: echo "::set-output name=artifact::$(sh ./target_rename.sh "${{ matrix.target }}" | head -n 1)"
      - name: Upload build artifacts
        uses: softprops/action-gh-release@v1
        with:
          tag_name: bin-${{ github.ref_name }}
          files: |
            ${{ steps.artifacts.outputs.artifact }}
